apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: digiv-fe
  namespace: "dev"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: digiv-fe
    spec:
      containers:
        - name: digiv-fe
          image: "asia.gcr.io/adiravirtualexpo/digivapp.fe:0.0.10-dev"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "300m"
              memory: "300Mi"
            requests:
              cpu: "300m"
              memory: "300Mi"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 80
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: "/health"
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
